### ISSUE TITLE
텍스트 전체선택 후 붙여넣기 하면 pre tag 까지 안에 붙여넣기 되는 현상

### ISSUE THREAD

**Issue by hywlss9** [Teo-Sprint-14th-1team/cherryblossom#118]
onInput event의 innerText 또는 contenteditable 관련 버그이지 않을까 싶습니다.

![image](https://user-images.githubusercontent.com/37681882/227075958-d9ca053b-6c0f-439d-877e-feb91ff57ab4.png)

**Comment by seunghoonKang** [comment]
@hywlss9 님. 말씀주신  contenteditable의 작성 위치 때문에 생긴 버그(#127)로 보입니다 .  
오류 제보 감사합니다  👍
